### ISSUE TITLE
[TODO List]

### ISSUE THREAD

**Issue by NE-SmallTown** [NE-SmallTown/Redux-Heaven#1]
- [ ] convert webpack to rollup
- [ ] open redux devtools of example in production
- [ ] add pretitter
- [ ] precommit hock
- [ ] prepublish hock
- [ ] use warning and invariant instead error and warn
- [ ] use [mock.js](http://mockjs.com/examples.html)
